### ISSUE TITLE
您好，請教拉取Alpine的問題

### ISSUE THREAD

**Issue by freedom5566** [MioYvo/py3-mysqlclient-alpine#1]
建置的時候常常會停在
```
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
```
然後就不動了，查了很久沒有頭緒
這似乎是docker內部容器網路的問題
我嘗試使用`curl http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz`是有成功的
請問有甚麼好想法嗎？

**Comment by MioYvo** [comment]
@freedom5566 可以尝试替换掉alpine包管理系统**apk**的源，换成速度更快的源
```
/ # cat /etc/apk/repositories
http://dl-cdn.alpinelinux.org/alpine/v3.7/main
http://dl-cdn.alpinelinux.org/alpine/v3.7/community
```

[官方源列表](https://git.alpinelinux.org/cgit/aports/tree/main/alpine-mirrors/mirrors.yaml)。

替换方法可以借鉴文件 _./Dockerfile-China_ 中的这一行
```
sed -i 's/dl-cdn.alpinelinux.org/mirror.tuna.tsinghua.edu.cn/g' /etc/apk/repositories
```
意义为在文件 _/etc/apk/repositories_ 中寻找文本`dl-cdn.alpinelinux.org`（默认源）， 替换为`mirror.tuna.tsinghua.edu.cn`（清华大学的源）

希望可以帮到你:)

**Comment by freedom5566** [comment]
謝謝，這有幫助，我試著找找看對我來說最快的源
